### ISSUE TITLE
When the map is initialized with zoom:1, the svg is out of place

### ISSUE THREAD

**Issue by Fil** [teralytics/Leaflet.D3SvgOverlay#11]
That's the same as bug #9 I think; just put `zoom:1` on line 24 at map initialization , and Swiss cities are in Norway (or anywhere else depending on your window size).

![capture d ecran 2015-09-08 10 39 26](https://cloud.githubusercontent.com/assets/7001/9730336/269f580c-5616-11e5-96e1-b5c6f04bb894.png)

**Comment by xEviL** [comment]
@Fil, thanks again for reporting.

I'm working on #1 which is a rewrite of most of code of the plugin, there this problem does not exist. It's almost finished, I will do the last checks and publish an update in a day or two.

For now have a look at: https://github.com/teralytics/Leaflet.D3SvgOverlay/blob/%231-v.2.1-animation-with-leaflet/L.D3SvgOverlay.js

Note that for Leaflet 0.7.x you would probably need to add:

```
L.Point.prototype._round = function(){return this;};
```

before accessing L.map(...) to remove the rounding of coordinates in the L.Point class, since this causes little lags and jumps on zooming.

**Comment by Fil** [comment]
Yes that new version solves the issue. Thanks a lot!

**Comment by Fil** [comment]
I've tried to plug the new `L.D3SvgOverlay.js` into the swiss example (removing `min` from the js call, and changing `zoom:8` to `zoom:1` on line 24), and I still have the problem.

(Sorry for the initial success report, it was because I forgot to open the window very large — this is what causes the bug, when the top of the map is below the top of the window).

**Comment by Fil** [comment]
I'm sorry I didn't see your patch 6 days ago. I tried to apply it and still have the bug (with Firefox, Safari, Chrome); I tried also with the whole file from the new branch and see the same problem: maybe I'm doing something wrong, I've pushed the files to https://enchanting-position.surge.sh

**Comment by xEviL** [comment]
@Fil, you're right, I forgot to update the projection code. For static example you can now just use the map.latLngToLayerPoint(...) to project coordinates. For drawing new objects after zoom has changed I'll have to fix the projection code.

**Comment by xEviL** [comment]
@Fil should be fixed now, in the branch https://github.com/teralytics/Leaflet.D3SvgOverlay/tree/%231-v.2.1-animation-with-leaflet

**Comment by Fil** [comment]
Yes it works! Thanks a lot!
