### ISSUE TITLE
Calling removeLayer() on L.D3SvgOverlay layer breaks map

### ISSUE THREAD

**Issue by jdgodchaux** [teralytics/Leaflet.D3SvgOverlay#5]
Hello!

Many thanks for a great tool to easily add D3 overlays to leaflet maps. I've run across a problem when attempting to remove layers added with L.D3SvgOverlay to a map. I've recreated the swiss cities example here to demonstrate the problem:

http://embed.plnkr.co/f8YQg4LTVBsmMvdKaams/preview

I've added:

```
map.on('zoomend', function(e) {
  if (map.getZoom() < 8) {
    map.removeLayer(citiesOverlay);
  }
});
```

so that when one zooms out one level from the starting zoom, the citiesOverlay layer is removed but the map breaks. One can no longer pan or zoom the map any further. 

Is there some other way to safely remove a map layer added with L.D3SvgOverlay, or is this a known issue with removeLayer() and L.D3SvgOverlay?

Thanks!
JD

**Comment by jdgodchaux** [comment]
One more thing to report with this problem. On another map I have where I have two layers, one just a run of the mill L.circleMarker and the other a L.D3SvgOverlay layer, I can remove the L.D3SvgOverlay layer and add the L.circleMarker layer with a time slider I've built, but zooming and panning break after the L.D3SvgOverlay layer is removed. It also breaks silently -- I don't see any error messages in the console to help debug.

**Comment by akauppi** [comment]
Hi, JD

Have you noticed the issue #1 I have over here? I reproduced the Swiss cities case with my own bridge code - that deals with any SVG library, not just D3. Its approach is different in the way that it doesn't change the underlying SVG DOM when scaling happens. Maybe your code will work with it?

I tried with the snippet you gave. Yes, overlay removed without any side effects.

Disclaimer: at this point, it's only available as a fork of Leaflet. It could be made into a plugin, like the D3 plugin is.

**Comment by jdgodchaux** [comment]
Hi Asko!

Thank you! I'll try out your leaflet fork and see if that does the trick. 

JD

**Comment by jdgodchaux** [comment]
Hi again Asko!

I looked at your fork of Leaflet and I didn't see a leaflet JS library that I can use directly. Do I need to build the library (I've not done that before) or is there one hidden in that repository I can use?

Thank you!!!
JD

**Comment by akauppi** [comment]
@jdgodchaux 
If you send me a msg at akauppi@gmail.com we can continue this discussion elsewhere (or open an issue in my fork pages).

Yes, you need to compile the fork. I haven't taken the time to make it a plugin (since that would mean also maintaining it, publicizing it and all). But there's no reason the code couldn't easily be made a plugin. I just haven't. For my own needs a forked Leaflet is enough.

I was also waiting to see if I get more people interested in using the code, first.

Note that the changes are in the [activeOverlay](https://github.com/akauppi/Leaflet/tree/activeOverlay) branch. There:

<pre>
$ jake
$ open debug/map/active-overlay.html 
$ open debug/map/swiss-cities.html
</pre>

**Comment by xEviL** [comment]
@jdgodchaux thanks for reporting the issue. Looks like unbinding of event listeners doesn't work as expected. Just commenting this part of the code fixes the issue: http://embed.plnkr.co/isWbcSOm41pVmmG7PX9x/preview

@akauppi please, see my response in #1

**Comment by jdgodchaux** [comment]
Thank you Kirill! That worked for me!
