### ISSUE TITLE
How to disable scaling of markers?

### ISSUE THREAD

**Issue by jrittelmeyer** [teralytics/Leaflet.D3SvgOverlay#6]
Hello,

First of all, great project. Very useful and clean code and exactly what I was looking for. So thanks for creating it.

I do have one question, however. I would like to be able to keep zoom animations enabled but NOT scale up the size of the nodes when zooming. That is to say: I want to zoom in on the map, and I want the translation animation to remain (we should see the nodes move into place as we zoom), but I want the nodes to stay the same size as we zoom.

The reason for this is that when the nodes grow so large at a high zoom level, it becomes hard to use for me. In some cases, I have nodes that are grouped very closely together and overlap, and I want to be able to zoom in on them close enough that they don't overlap anymore. Each node has a popover that should be easily accessibly by zooming in far enough.

Is there a simple way for me to hack that functionality in? I tried simply commenting out the scale animation code, but that makes the translation animation look weird and jumpy.

Thanks in advance!

**Comment by xEviL** [comment]
@jrittelmeyer,

the whole SVG overlay is scaled and moved on zooming and panning. To keep you markers of the same size you would have to code up their shrinking/growing on zooming.

If you found a better way to deal with the problem, please share your code, we will be happy to incorporate the changes into L.D3SvgOverlay.

Kirill

**Comment by akauppi** [comment]
Hi, @jrittelmeyer 
My contribution has been discussed [elsewhere](https://github.com/teralytics/Leaflet.D3SvgOverlay/issues/1) here, so I'm not repeating those words. I think it would help you. Please have a look at the other issue and get in touch if you need more help. 

> ... It lets Leaflet run in its world, and anything SVG run in its. It makes peace between these two domains so that e.g. zooming in Leaflet does not affect anything in the SVG domain.

**Comment by xEviL** [comment]
A wider answer to this question before closing:

When zooming two things can happen: either one reprojects the element geometries into the new zoom level (elements features like size remain constant) or one scales the whole overlay (but then elements shrink/expand and one needs to adjust for that if it's desirable).

Since reprojection of the geometries is computationally more demanding, scaling and adjusting the size of elements is an easier and quicker way:

```
    ...
    updSel.
        .attr("r", 5 / this._scale)
```

The code above will set a radius (for SVG circle element) to always be 5 pixels.
