### ISSUE TITLE
Change projection so that map is oriented with Americas on right?

### ISSUE THREAD

**Issue by dsabsay** [teralytics/Leaflet.D3SvgOverlay#7]
This plugin works great for me so far. However, I would like to be able to draw an SVG layer where the Americas are on the "right" side of the screen and the other continents are on the left.

![](http://i.stack.imgur.com/1Rxqa.png)

More specifically, the tiled map from Leaflet displays a tiled version of the map, which allows a user to position it so that they can view it with Americas on the right of the screen, and everything else on the left. However, the projection only projects the points based on an orientation that puts the Americas on the left (relative to the other continents).

I am thinking that the projection calculation itself would need to be changed but I'm not quite sure how to go about that. 

Is there another easy way of doing this? Or would the projection calculation itself have to be modified?

Thanks in advance.

**Comment by xEviL** [comment]
@dsabsay, it's an interesting question. So Leaflet map is endless, you can pan it forever, but overlay is always only in the "first" world (-180,+180 longitude). E.g. http://leafletjs.com/examples/choropleth.html here it's the same problem.

I suppose you can modify this behavior by changing the projection. Otherwise, a quick hack would be to add 360 deg to all of the longitudes that are in the western hemisphere (depending on your needs, e.g. for zero meridian: if (lon < 0.0) {lon = lon + 360;}). I didn't test this, but if Leaflet's projection doesn't do the modulo 180 or 360 on the longitudes, this should work for you.

Of course this feature has a much wider use, so consider adding this functionality to the projection and contributing or at least filing a bug/feature request with Leaflet.
